/**
 * Created by randika on 11/30/2014.
 */
const USER = 1;
const SHOP = 2;
const USER_COLLECTION = "USER";
const SHOP_COLLECTION = "SHOP";
const SHOP_BRANCH = "SHOPBRANCH";
const SHOP_USER= "SHOPUSER";
const SUB_ITEM_COLLECTION = "SUBITEMS";
const PROFILE_COLLECTION = "PROFILE";
const ENTITLEMENTS_COLLECTION = "ENTITLEMENTS";
const MAIN_ITEM_COLLECTION = "MAINITEMS";
const PROMOTION_COLLECTION = "PROMOTIONS";
const MESSAGE = "MESSAGE";
const BANNER_IMAGE = "BANNERIMAGE";
const BLOG_COLLECTION = "BLOG";
const DOC_COUNT = "COUNT";
const MAX_DISTANCE = 0.90;
const PASSWORD_SEPARATOR = "$";
const ON_SALE = 1;
const NEW_PRODUCT = 2;
const TOP_RATED = 3;
const HASHING_ALGO = "SHA1";

const ERROR_INVALID_PARAMETER = "Invalid Parameters";
const ERROR_NOT_AUTHORIZED = "You are not authorized";
const ERROR_FAIL_AUTHORIZATION_EXP_DATE = "Authorization expired";


module.exports.USER = USER;
module.exports.SHOP = SHOP;
module.exports.SHOP_BRANCH = SHOP_BRANCH;
module.exports.SHOP_USER = SHOP_USER;
module.exports.MAX_DISTANCE = MAX_DISTANCE;
module.exports.USER_COLLECTION = USER_COLLECTION;
module.exports.SHOP_COLLECTION = SHOP_COLLECTION;
module.exports.SUB_ITEM_COLLECTION = SUB_ITEM_COLLECTION;
module.exports.PROFILE_COLLECTION = PROFILE_COLLECTION;
module.exports.ENTITLEMENTS_COLLECTION = ENTITLEMENTS_COLLECTION;
module.exports.MAIN_ITEM_COLLECTION = MAIN_ITEM_COLLECTION;
module.exports.PROMOTION_COLLECTION = PROMOTION_COLLECTION;
module.exports.MESSAGE = MESSAGE;
module.exports.BANNER_IMAGE = BANNER_IMAGE;
module.exports.BLOG_COLLECTION = BLOG_COLLECTION;
module.exports.PASSWORD_SEPARATOR = PASSWORD_SEPARATOR;
module.exports.ON_SALE = ON_SALE;
module.exports.NEW_PRODUCT = NEW_PRODUCT;
module.exports.TOP_RATED = TOP_RATED;
module.exports.HASHING_ALGO = HASHING_ALGO;
module.exports.DOC_COUNT = DOC_COUNT;

module.exports.ERROR_INVALID_PARAMETER = ERROR_INVALID_PARAMETER;
module.exports.ERROR_NOT_AUTHORIZED = ERROR_NOT_AUTHORIZED;
module.exports.ERROR_FAIL_AUTHORIZATION_EXP_DATE = ERROR_FAIL_AUTHORIZATION_EXP_DATE;
