/**
 * Created by randika on 11/30/2014.
 */
const USER = 1;
const SHOP = 2;
const USER_COLLECTION = "USER";
const SHOP_COLLECTION = "SHOP";
const SUB_ITEM_COLLECTION = "SUBITEMS";
const MAIN_ITEM_COLLECTION = "MAINITEMS";
const PROMOTION_COLLECTION = "PROMOTIONS";
const MESSAGE = "MESSAGE";
const BLOG_COLLECTION = "BLOG";
const MAX_DISTANCE = 0.90;
const PASSWORD_SEPARATOR = "$";
const HASHING_ALGO = "SHA1";

module.exports.USER = USER;
module.exports.SHOP = SHOP;
module.exports.MAX_DISTANCE = MAX_DISTANCE;
module.exports.USER_COLLECTION = USER_COLLECTION;
module.exports.SHOP_COLLECTION = SHOP_COLLECTION;
module.exports.SUB_ITEM_COLLECTION = SUB_ITEM_COLLECTION;
module.exports.MAIN_ITEM_COLLECTION = MAIN_ITEM_COLLECTION;
module.exports.PROMOTION_COLLECTION = PROMOTION_COLLECTION;
module.exports.MESSAGE = MESSAGE;
module.exports.BLOG_COLLECTION = BLOG_COLLECTION;
module.exports.PASSWORD_SEPARATOR = PASSWORD_SEPARATOR;
module.exports.HASHING_ALGO = HASHING_ALGO;
